import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Tasty Bites | An Ultimate Restro App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-main text-main-foreground"
        suppressHydrationWarning
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
